---
# tasks/main.yml for rsnapshot
- name: set rsnapshot to state "{{ wtd_rsnapshot_state }}"
  package:
    name: "{{ wtd_rsnapshot_packages }}"
    state: "{{ wtd_rsnapshot_state }}"

- name: Include configuration for notification
  include_tasks: notify.yml
  when: wtd_rsnapshot_notify

- name: Include configuration for one rsnapshot task
  include_tasks: one.yml
  when: wtd_rsnapshot_state == "present" and not wtd_rsnapshot_config_multi_enabled

- name: Include configuration for multiple rsnapshot tasks
  include_tasks: multi.yml
  when: wtd_rsnapshot_state == "present" and wtd_rsnapshot_config_multi_enabled
