---
# tasks/main.yml for rsnapshot
- name: set rsnapshot to state "{{ wtd_rsnapshot_state }}"
  package:
    name: "{{ wtd_rsnapshot_packages }}"
    state: "{{ wtd_rsnapshot_state }}"

- include_tasks: notify.yml
  when: wtd_rsnapshot_notify

- include_tasks: one.yml
  when: wtd_rsnapshot_state == "present" and not wtd_rsnapshot_multi
- include_tasks: multi.yml
  when: wtd_rsnapshot_state == "present" and wtd_rsnapshot_multi
