- name: load multi-vars
  include_vars:
    file: multi.yml

- name: set configurations for rsnapshot
  template:
    src: "rsnapshot-multi.conf.j2"
    dest: "/etc/rsnapshot-{{ item.name }}.conf"
    mode: 0644
    owner: root
    group: root
    #validate: "rsnapshot -c %s configtest"
  with_items:
    - "{{ wtd_rsnapshot_config_multi }}"

      #- name: "copy templates"
      #  delegate_to: 127.0.0.1
      #  copy:
      #    src: "{{ role_path }}/templates/rsnapshot.timer.j2"
      #    dest: "{{ role_path }}/templates/rsnapshot-{{ item.name }}.timer.j2"
      #  with_items:
      #    - "{{ wtd_rsnapshot_config_multi }}"

- debug:
    msg: "{{ wtd_rsnapshot_config_multi }}"
  
- name: "Create Timers for Backup"
  template:
    src: "rsnapshot-multi.timer.j2"
    #dest: "/etc/systemd/system/rsnapshot-{{ item.name }}.timer"
    dest: "/etc/systemd/system/rsnapshot-{{ item.0.name }}-{{ item.1.name }}.timer"
    owner: root
    group: root
    mode: 0644
    #with_items:
    #- "{{ wtd_rsnapshot_config_multi }}"
    #with_nested:
    #  - "{{ wtd_rsnapshot_config_multi }}"
    #  - "{{ item.0.retains }}"
  with_subelements:
    - "{{ wtd_rsnapshot_config_multi }}"
    - "retains"

- name: "Create Service for Backup"
  template:
    src: "rsnapshot@-multi.service.j2"
    dest: "/etc/systemd/system/rsnapshot-{{ item.name }}@.service"
    owner: root
    group: root
    mode: 0644
  when: wtd_rsnapshot_state == "present" and wtd_rsnapshot_multi
  with_items:
    - "{{ wtd_rsnapshot_config_multi }}"

- name: enable and start service rsnapshot timer
  systemd:
    name: "rsnapshot-{{ item.0.name }}-{{ item.1.name }}.timer"
    state: started
    enabled: yes
  with_subelements:
    - "{{ wtd_rsnapshot_config_multi }}"
    - "retains"
