- name: set configurations for rsnapshot
  template:
    src: "rsnapshot-multi.conf.j2"
    dest: "/etc/rsnapshot-{{ item.name }}.conf"
    mode: 0644
    owner: root
    group: root
    validate: "rsnapshot -c %s configtest"
  with_items:
    - "{{ wtd_rsnapshot_config_multi }}"

- name: "Create Timers for Backup"
  template:
    src: "rsnapshot-multi.timer.j2"
    dest: "/etc/systemd/system/rsnapshot-{{ item.0.name }}-{{ item.1.name }}.timer"
    owner: root
    group: root
    mode: 0644
  with_subelements:
    - "{{ wtd_rsnapshot_config_multi }}"
    - "retains"

- name: "Create Service for Backup"
  template:
    src: "rsnapshot@-multi.service.j2"
    dest: "/etc/systemd/system/rsnapshot-{{ item.name }}@.service"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ wtd_rsnapshot_config_multi }}"

- name: enable and start service rsnapshot timer
  systemd:
    name: "rsnapshot-{{ item.0.name }}-{{ item.1.name }}.timer"
    state: started
    enabled: yes
  with_subelements:
    - "{{ wtd_rsnapshot_config_multi }}"
    - "retains"
